import assert from 'node:assert/strict';
import { test, mock } from 'node:test';
import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { hydrateOperatingRoomModels } from '../../vendor/orms-spatial-editor/src/room-assets.js';
import { setRoomActivity, setRoomStatus, setRoomSelected } from '../../vendor/orms-spatial-editor/src/geometry.js';

test('shared GLB materials are graded once, while live walls and lights remain per-room', async () => {
  const source = new THREE.Group();
  const steel = new THREE.MeshStandardMaterial({ color: 0x637798 });
  steel.name = 'steel';
  const originalSteel = steel.color.clone();
  const wall = new THREE.MeshStandardMaterial({ color: 0x59688a });
  wall.name = 'wall';
  for (let index = 0; index < 10; index++) source.add(new THREE.Mesh(new THREE.BoxGeometry(), steel));
  source.add(new THREE.Mesh(new THREE.BoxGeometry(), wall));
  const load = mock.method(GLTFLoader.prototype, 'loadAsync', async () => ({ scene: source }));
  const rooms = ['ready', 'active'].map(id => ({ id, name: id, type: 'operating', width: 7.03, height: 3.09, depth: 6.825 }));
  const entities = new Map(rooms.map(room => {
    const group = new THREE.Group();
    group.userData = { entity: 'room', operationalActive: room.id === 'active' };
    const strip = new THREE.Mesh(new THREE.BoxGeometry(), new THREE.MeshStandardMaterial());
    strip.userData.selectionLight = true;
    strip.visible = room.id === 'active';
    group.add(strip);
    return [room.id, group];
  }));
  assert.equal(await hydrateOperatingRoomModels(entities, rooms), true);
  assert.equal(load.mock.callCount(), 1);
  assert.ok(steel.color.equals(originalSteel.lerp(new THREE.Color(0xa1acc6), 0.3)));
  assert.equal(entities.get('ready').children[0].visible, false, 'hydration must not turn on ready-room strips');
  assert.equal(entities.get('active').children[0].visible, true);
  const walls = rooms.map(room => {
    let result;
    entities.get(room.id).traverse(mesh => { if (mesh.material?.name === 'wall') result = mesh.material; });
    return result;
  });
  assert.notEqual(walls[0], walls[1]);
  assert.equal(walls[0].customProgramCacheKey(), 'room-satin-v1-wall');
  const readyColor = walls[0].color.clone();
  setRoomStatus(entities.get('active'), '#e52b52', true);
  assert.ok(walls[0].color.equals(readyColor), 'changing one room does not tint its neighbour');
  assert.ok(!walls[1].color.equals(readyColor));
  setRoomStatus(entities.get('active'), null, true);
  assert.equal(walls[1].color.getHex(), readyColor.getHex(), 'ready state restores the neutral surface');
  setRoomActivity(entities.get('active'), false);
  assert.equal(entities.get('active').children[0].visible, false);
  setRoomActivity(entities.get('active'), true);
  assert.equal(entities.get('active').children[0].visible, true);
  const presentation = entities.get('active');
  presentation.userData.hideActivityStrips = true;
  setRoomSelected(presentation, true, 0xffda28, { showLight: false, tintSurfaces: false });
  assert.equal(presentation.children[0].visible, false, 'dashboard selection never adds yellow under-room lines');
  setRoomActivity(presentation, false);
  setRoomActivity(presentation, true);
  setRoomSelected(presentation, false);
  assert.equal(presentation.children[0].visible, false, 'activity and deselection keep strips hidden');
  assert.equal(presentation.userData.operationalActive, true, 'warm interior light remains driven by activity');
  const unmounted = new THREE.Group();
  assert.equal(await hydrateOperatingRoomModels(new Map([['ready', unmounted]]), rooms, { shouldApply: () => false }), false);
  assert.equal(unmounted.children.length, 0, 'stale async loads do not alter disposed scenes');
  load.mock.restore();
});
